#!/usr/bin/env python
#python -m authWatch $*

import sys
import os
import argparse
import authwatch.watcher


if __name__ == "__main__":
	#check root or not
	if os.getenv('USER') != 'root':
		print "This tool must be run as root. It just simply won't work otherwise."
		sys.exit(1)

	parser = argparse.ArgumentParser(description='This tool/utility allows you to monitor the wifi tubes for auth, deauth or assoc requests. You can optionally output the data to a dump file.\n\nAircrack suite and scapy are required to use this tool.')
	parser.add_argument('-u', '--authignore', action='store_true', required=False, help='Do not monitor for auth.')
	parser.add_argument('-a', '--assocignore', action='store_true', required=False, help='Do not monitor for assoc.')
	parser.add_argument('-d', '--deauthignore', action='store_true', required=False, help='Do not monitor for deauth.')
	parser.add_argument('-D', '--dumpfile', default='', required=False, help='Specifiy where you would like to locate the dump file......so you can use it later. >:)')
	parser.add_argument('-v', '--verbose', required=False, action='store_true', help='Gives verbose feedback.')

	parser.add_argument('interface')
	args = parser.parse_args()
	authwatch.watcher.main(args)
